FROM ubuntu:latest
RUN apt-get update && apt-get install -y openssh-client sshpass

# Cria diretório pro ssh funcionar
RUN mkdir /var/run/sshd

# copiar script para dentro do conteiner
COPY copiar_arquivo.sh /copiar_arquivo.sh

# tornar executável
RUN chmod +x /copiar_arquivo.sh

# Pegar o arquivo do host e copiar para o container, que o copiará para o container do fedora
COPY arquivo.txt /arquivo.txt

EXPOSE 22
CMD ["/bin/bash", "/copiar_arquivo.sh"]

